-- ─────────────────────────────────────────────────────────────────
-- Module 9 — Your Personal Research Assistant
-- ─────────────────────────────────────────────────────────────────
-- Inserts the BYOK Gemini educational module into the academy tables
-- (academy_modules + academy_lessons + academy_questions). Idempotent:
-- safe to re-run; existing Module 9 rows are deleted and re-inserted
-- so an admin tweak in the dashboard never collides with a re-seed.
--
-- Adds two new columns to academy_modules that the original schema was
-- missing per the Module 9 build spec:
--   is_pro              boolean — gate flag (currently passes via usePlan
--                       OPEN_FREE during beta; primed for paid-tier launch)
--   points_on_complete  integer — points granted via awardPoints when the
--                       quiz is passed
--
-- Tamil section content + HI/ML/TA quiz-option translations were
-- machine-generated by Claude during the build, matching the
-- code-mixed style of existing Tamil rows in academy_lessons. Per
-- user decision: machine-translate (recommended). Mark `updated_at`
-- so a future human-translation pass can re-stamp the row.
-- ─────────────────────────────────────────────────────────────────


-- ═════════════════════════════════════════════════════════════════
-- 1. Schema extensions on academy_modules
-- ═════════════════════════════════════════════════════════════════
ALTER TABLE academy_modules ADD COLUMN IF NOT EXISTS is_pro             boolean NOT NULL DEFAULT false;
ALTER TABLE academy_modules ADD COLUMN IF NOT EXISTS points_on_complete integer NOT NULL DEFAULT 0;


-- ═════════════════════════════════════════════════════════════════
-- 2. Module row
-- ═════════════════════════════════════════════════════════════════
-- Insert/update the module-level row. ON CONFLICT (id) handles re-runs.
INSERT INTO academy_modules (
  id, title_en, title_hi, title_ml, title_ta,
  subtitle_en, subtitle_hi, subtitle_ml, subtitle_ta,
  icon, duration, sort_order, is_published, pass_mark, total_questions,
  is_pro, points_on_complete
) VALUES (
  'research_assistant',
  'Your Personal Research Assistant',
  'आपका निजी रिसर्च असिस्टेंट',
  'നിങ്ങളുടെ Personal Research Assistant',
  'உங்கள் தனிப்பட்ட ஆராய்ச்சி உதவியாளர்',
  'Bring your own Gemini key. Private. Unlimited. Yours.',
  'अपनी Gemini key लाएँ। निजी। असीमित। आपकी।',
  'നിങ്ങളുടെ സ്വന്തം Gemini key കൊണ്ടുവരൂ. Private. Unlimited. നിങ്ങളുടേത്.',
  'உங்க சொந்த Gemini key-ஐ கொண்டு வாங்க. Private. வரம்பற்றது. உங்களோடது.',
  '🔬',
  '10 min',
  9,
  true,
  4,
  5,
  true,   -- is_pro
  40      -- points_on_complete
)
ON CONFLICT (id) DO UPDATE SET
  title_en           = EXCLUDED.title_en,
  title_hi           = EXCLUDED.title_hi,
  title_ml           = EXCLUDED.title_ml,
  title_ta           = EXCLUDED.title_ta,
  subtitle_en        = EXCLUDED.subtitle_en,
  subtitle_hi        = EXCLUDED.subtitle_hi,
  subtitle_ml        = EXCLUDED.subtitle_ml,
  subtitle_ta        = EXCLUDED.subtitle_ta,
  icon               = EXCLUDED.icon,
  duration           = EXCLUDED.duration,
  sort_order         = EXCLUDED.sort_order,
  is_published       = EXCLUDED.is_published,
  pass_mark          = EXCLUDED.pass_mark,
  total_questions    = EXCLUDED.total_questions,
  is_pro             = EXCLUDED.is_pro,
  points_on_complete = EXCLUDED.points_on_complete,
  updated_at         = now();


-- ═════════════════════════════════════════════════════════════════
-- 3. Lessons (9 sections)
-- ═════════════════════════════════════════════════════════════════
-- Idempotent: wipe + re-insert. The user_module_progress table is keyed
-- on module_id, not on individual lesson rows, so re-seeding lessons
-- doesn't reset anyone's completion state.
DELETE FROM academy_lessons WHERE module_id = 'research_assistant';

INSERT INTO academy_lessons (module_id, sort_order, title, content_en, content_hi, content_ml, content_ta, visual_type, is_published) VALUES
-- ── Section 1 — The Story ─────────────────────────────────────
('research_assistant', 1, 'The Story',
$en$Imagine you have a friend.

This friend has read every book about stock market analysis. They understand cycle analysis deeply. They are available 24 hours a day. They never get tired of your questions. They never judge you for asking something basic. And they know exactly which phase HONASA is in right now.

This friend exists. And you can have them for free.

This module shows you how.$en$,
$hi$एक बात सोचिए।

आपका एक दोस्त है।

यह दोस्त stock market analysis की हर किताब पढ़ चुका है। Cycle analysis उसे बहुत अच्छी तरह समझ आती है। दिन के 24 घंटे उपलब्ध है। आपके सवालों से कभी थकता नहीं। Basic सवाल पूछने पर judge नहीं करता। और अभी HONASA किस phase में है — यह भी उसे पता है।

यह दोस्त मौजूद है। और आप उसे मुफ्त में पा सकते हैं।

यह module आपको बताएगा कैसे।$hi$,
$ml$ഒരു കാര്യം ഒന്ന് സങ്കൽപ്പിക്കൂ.

നിങ്ങൾക്ക് ഒരു സുഹൃത്ത് ഉണ്ട്.

ഈ സുഹൃത്ത് stock market analysis നെ കുറിച്ചുള്ള എല്ലാ പുസ്തകങ്ങളും വായിച്ചിട്ടുണ്ട്. Cycle analysis അവർക്ക് നന്നായി അറിയാം. ദിവസം 24 മണിക്കൂറും ലഭ്യമാണ്. ചോദ്യങ്ങൾ കേൾക്കാൻ ഒരിക്കലും മടുക്കില്ല. Basic ചോദ്യം ചോദിച്ചാലും judge ചെയ്യില്ല. HONASA ഇപ്പോൾ ഏത് phase ൽ ആണെന്നും അവർക്ക് അറിയാം.

ഈ സുഹൃത്ത് ഉണ്ട്. നിങ്ങൾക്ക് അവരെ free ൽ ലഭിക്കും.

ഈ module അത് എങ്ങനെ ചെയ്യണം എന്ന് കാണിക്കും.$ml$,
$ta$ஒரு கணம் கற்பனை செய்துங்க.

உங்களுக்கு ஒரு நண்பர் இருக்கார்.

இவர் stock market analysis-ஓட எல்லா books-உம் படிச்சிருக்கார். Cycle analysis-ஐ அழமா புரிஞ்சு வச்சிருக்கார். 24 மணி நேரமும் கிடைக்கிறார். உங்க கேள்விகள்ல சோர்வே இல்ல. Basic கேள்வி கேட்டா judge பண்ண மாட்டார். HONASA இப்போ எந்த phase-ல இருக்குனு துல்லியமா அவருக்குத் தெரியும்.

இந்த நண்பர் உண்மையில் இருக்கார். இலவசமா உங்க கூட பயன்படுத்தலாம்.

இந்த module அதை எப்படினு காட்டும்.$ta$,
'none', true),

-- ── Section 2 — What is Gemini? ───────────────────────────────
('research_assistant', 2, 'What is Gemini?',
$en$Gemini is Google's AI assistant.

You have probably used Google Search. Gemini is like Google Search but instead of showing you links — it actually reads everything and gives you an answer.

It can understand complex questions.
It can explain things simply.
It can work with data you give it.

When you give Gemini the data about a stock — its phase, criteria score, sector — Gemini can answer your questions about that stock intelligently.

Your questions. Your answers. Private.$en$,
$hi$Gemini Google का AI assistant है।

आपने Google Search तो इस्तेमाल किया होगा। Gemini उसी जैसा है — बस फर्क यह है कि यह links दिखाने की जगह सीधे जवाब देता है।

जटिल सवाल समझता है।
सरल भाषा में समझाता है।
आप जो data देते हैं उससे काम करता है।

जब आप किसी stock का data Gemini को देते हैं — उसका phase, criteria score, sector — तो Gemini उस stock के बारे में आपके किसी भी सवाल का जवाब दे सकता है।

आपके सवाल। आपके जवाब। बिल्कुल private।$hi$,
$ml$Gemini Google ന്റെ AI assistant ആണ്.

Google Search ഉപയോഗിച്ചിട്ടുണ്ടോ? Gemini അതുപോലെ — പക്ഷേ links കാണിക്കുന്നതിന് പകരം നേരിട്ട് ഉത്തരം പറയും.

സങ്കീർണ്ണമായ ചോദ്യങ്ങൾ മനസ്സിലാക്കും.
ലളിതമായ ഭാഷയിൽ വിശദീകരിക്കും.
നിങ്ങൾ കൊടുക്കുന്ന data വിശകലനം ചെയ്യും.

ഒരു stock ന്റെ data — phase, criteria score, sector — Gemini ന് കൊടുത്താൽ ആ stock നെ കുറിച്ചുള്ള ഏത് ചോദ്യത്തിനും ഉത്തരം കിട്ടും.

നിങ്ങളുടെ ചോദ്യങ്ങൾ. നിങ്ങളുടെ ഉത്തരങ്ങൾ. പൂർണ്ണ സ്വകാര്യത.$ml$,
$ta$Gemini-ன்னா Google-ஓட AI assistant.

Google Search-ஐ நீங்க பயன்படுத்தி இருப்பீங்க. Gemini கிட்டத்தட்ட அதே மாதிரி — ஆனா links-ஐ காட்டாம, நேரடியா பதிலையே சொல்லும்.

சிக்கலான கேள்விகளை புரிஞ்சுக்கும்.
எளிய மொழியில் விளக்கும்.
நீங்க கொடுக்கிற data-ஓட வேலை செய்யும்.

ஒரு stock-ஓட data — phase, criteria score, sector — Gemini-க்கு கொடுத்தா, அந்த stock பத்தி உங்க எல்லா கேள்விகளுக்கும் அறிவாய்வா பதில் தரும்.

உங்க கேள்விகள். உங்க பதில்கள். முழுசா private.$ta$,
'none', true),

-- ── Section 3 — What is an API key? ───────────────────────────
('research_assistant', 3, 'What is an API key?',
$en$Think of it like a library card.

A library has thousands of books. Anyone can read them. But you need a library card to take books home.

Gemini has enormous intelligence. Google makes it available to anyone. But you need a key to use it from your own apps.

The key is just a long password. Something like:
AIzaSyD_example_1234567

You get one for free from Google. You paste it into PineX once. That is it. Your personal analyst is ready.$en$,
$hi$इसे library card की तरह समझिए।

Library में हजारों किताबें होती हैं। कोई भी पढ़ सकता है। लेकिन घर ले जाने के लिए library card चाहिए।

Gemini की intelligence बहुत बड़ी है। Google ने इसे सबके लिए उपलब्ध किया है। लेकिन अपने app में इस्तेमाल करने के लिए एक key चाहिए।

यह key बस एक लंबा password है। कुछ ऐसा:
AIzaSyD_example_1234567

Google से मुफ्त में मिलती है। PineX में एक बार paste करें। बस। आपका personal analyst तैयार।$hi$,
$ml$Library card പോലെ ഒന്ന് ആണെന്ന് ചിന്തിക്കൂ.

Library ൽ ആയിരക്കണക്കിന് പുസ്തകങ്ങൾ ഉണ്ട്. ആർക്കും വായിക്കാം. പക്ഷേ വീട്ടിൽ കൊണ്ടുപോകാൻ library card വേണം.

Gemini ന്റെ intelligence Google ഉണ്ടാക്കിയതാണ്. ആർക്കും use ചെയ്യാം. പക്ഷേ നിങ്ങളുടെ app ൽ ഉപയോഗിക്കാൻ ഒരു key വേണം.

ആ key ഒരു long password പോലെ ആണ്:
AIzaSyD_example_1234567

Google ൽ നിന്ന് free ൽ കിട്ടും. ഒരു തവണ PineX ൽ paste ചെയ്താൽ മതി. അത്ര തന്നെ.$ml$,
$ta$Library card மாதிரி ஒன்று-னு நினைச்சுக்குங்க.

Library-ல ஆயிரக்கணக்கான books இருக்கும். எல்லாருக்கும் படிக்க உரிமை இருக்கு. ஆனா வீட்டுக்கு எடுத்துப் போக library card தேவை.

Gemini-ஓட intelligence-ஐ Google உருவாக்கி இருக்கு. யாரும் பயன்படுத்தலாம். ஆனா உங்க app-ல இருந்து பயன்படுத்த ஒரு key வேணும்.

அந்த key ஒரு long password மாதிரி:
AIzaSyD_example_1234567

Google-ல free-ஆ கிடைக்கும். ஒரு தடவ PineX-ல paste பண்ணினா போதும். அவ்வளவுதான்.$ta$,
'none', true),

-- ── Section 4 — How is this safe? ─────────────────────────────
('research_assistant', 4, 'How is this safe?',
$en$This is the most important part.

When you save your key in PineX:
It stays on your phone or computer. Only on your device. Never anywhere else.

It never goes to PineX servers.
It never goes to Supabase.
It never goes anywhere.

When you ask a question:
Your device sends the question directly to Google. Not through PineX. Not through any middleman.

PineX never sees your question.
PineX never sees the answer.
PineX never sees your key.

It is like using your own phone to call someone. PineX is just the app. The conversation is yours.$en$,
$hi$यह सबसे जरूरी हिस्सा है।

जब आप PineX में key save करते हैं:
सिर्फ आपके phone या computer में रहती है। कहीं नहीं जाती।

PineX के servers पर नहीं जाती।
कहीं store नहीं होती।

जब आप कोई सवाल पूछते हैं:
आपका device सीधे Google को भेजता है।
PineX के through नहीं।
बीच में कोई नहीं।

PineX आपका सवाल नहीं देखता।
PineX जवाब नहीं देखता।
PineX आपकी key नहीं देखता।

जैसे अपने phone से किसी को call करना। PineX बस वो app है। बातचीत आपकी है।$hi$,
$ml$ഇത് ഏറ്റവും പ്രധാനപ്പെട്ട ഭാഗം.

നിങ്ങൾ PineX ൽ key save ചെയ്യുമ്പോൾ:
നിങ്ങളുടെ phone അല്ലെങ്കിൽ computer ൽ മാത്രം ഉണ്ടാകും. ഒരിടത്തേക്കും പോകില്ല.

PineX server ലേക്ക് പോകില്ല.
Supabase ലേക്ക് പോകില്ല.
ഒരിടത്തേക്കും പോകില്ല.

നിങ്ങൾ ഒരു ചോദ്യം ചോദിക്കുമ്പോൾ:
നിങ്ങളുടെ device നേരിട്ട് Google ലേക്ക് ചോദ്യം അയക്കും. PineX വഴി അല്ല.

PineX നിങ്ങളുടെ ചോദ്യം കാണില്ല.
PineX ഉത്തരം കാണില്ല.
PineX നിങ്ങളുടെ key കാണില്ല.

സ്വന്തം phone ൽ ആരെങ്കിലുമൊരാളെ call ചെയ്യുന്നതുപോലെ. PineX ആ conversation കേൾക്കില്ല.$ml$,
$ta$இது மிக முக்கியமான பகுதி.

PineX-ல key save பண்ணும்போது:
உங்க phone-ல அல்லது computer-ல மட்டும் இருக்கும். வேற எங்கேயும் போகாது.

PineX servers-க்கு போகாது.
Supabase-க்கு போகாது.
எங்கேயும் போகாது.

நீங்க கேள்வி கேக்கும்போது:
உங்க device நேரடியா Google-க்கு கேள்வியை அனுப்பும். PineX வழியா இல்ல. நடுவில யாரும் இல்ல.

PineX உங்க கேள்வியை பார்க்காது.
PineX பதிலை பார்க்காது.
PineX உங்க key-ஐ பார்க்காது.

சொந்த phone-ல யாருக்காவது call பண்றது மாதிரி. PineX வெறும் app தான். பேச்சு உங்களோடது.$ta$,
'none', true),

-- ── Section 5 — Getting your free key ─────────────────────────
('research_assistant', 5, 'Getting your free key',
$en$Step 1:
Go to aistudio.google.com
Use your Google account — the same one you use for Gmail.

Step 2:
Click "Get API key" in the top menu.
Click "Create API key".
Click "Create API key in new project".

Step 3:
A long code appears on screen — a long key from aistudio.google.com.
Newer keys start with AQ. and older ones start with AIzaSy.
Copy it. All of it.

Step 4:
Open PineX.
Go to Settings → Research Assistant.
Paste your key in the box.
Click the SAVE button.
(You must click Save — the key is not stored until you click it.)

Done. Your personal analyst is ready.$en$,
$hi$Step 1:
aistudio.google.com पर जाएं।
Gmail account से login करें।

Step 2:
"Get API key" पर click करें।
"Create API key" पर click करें।
"Create API key in new project" पर click करें।

Step 3:
Screen पर एक लंबा code दिखेगा — aistudio.google.com का key।
नये keys AQ. से शुरू होते हैं, पुराने AIzaSy से।
उसे copy करें। पूरा।

Step 4:
PineX खोलें।
Settings → Research Assistant पर जाएं।
Box में paste करें।
SAVE button पर click करें।
(Save click करना जरूरी है — बिना Save के key store नहीं होती।)

बस। आपका personal analyst तैयार।$hi$,
$ml$Step 1:
aistudio.google.com ൽ പോകൂ.
Gmail account ഉപയോഗിച്ച് login ചെയ്യൂ.

Step 2:
"Get API key" click ചെയ്യൂ.
"Create API key" click ചെയ്യൂ.
"Create API key in new project" click ചെയ്യൂ.

Step 3:
Screen ൽ ഒരു long code appear ആകും — aistudio.google.com ന്റെ key.
പുതിയ keys AQ. ൽ തുടങ്ങും, പഴയവ AIzaSy ൽ.
അത് മുഴുവൻ copy ചെയ്യൂ.

Step 4:
PineX തുറക്കൂ.
Settings → Research Assistant ൽ പോകൂ.
Box ൽ paste ചെയ്യൂ.
SAVE button click ചെയ്യൂ.
(Save click ചെയ്യണം — click ചെയ്തില്ലെങ്കിൽ key store ആകില്ല.)

തീർന്നു. Personal analyst ready.$ml$,
$ta$Step 1:
aistudio.google.com-க்கு போங்க.
Gmail account use பண்ணி login செய்யுங்க.

Step 2:
"Get API key"-ஐ click செய்யுங்க.
"Create API key"-ஐ click செய்யுங்க.
"Create API key in new project"-ஐ click செய்யுங்க.

Step 3:
Screen-ல ஒரு நீளமான code தோணும் — aistudio.google.com-ன் key.
புது keys AQ.-ல தொடங்கும், பழசு AIzaSy-ல.
அதை முழுசா copy செய்யுங்க.

Step 4:
PineX-ஐ திறங்க.
Settings → Research Assistant-க்கு போங்க.
Box-ல paste செய்யுங்க.
SAVE button-ஐ click செய்யுங்க.
(Save click பண்ணணும் — click பண்ணாம key store ஆகாது.)

முடிஞ்சது. உங்க personal analyst ready.$ta$,
'none', true),

-- ── Section 6 — What to ask ───────────────────────────────────
('research_assistant', 6, 'What to ask',
$en$Questions that work beautifully:

"HONASA has been in an advancing trend for 47 days. What does cycle analysis say about stocks at this stage of an advance?"

"The Pharma sector has 71% breadth. How does broad sector participation affect individual stock behaviour?"

"I am looking at BIOCON which has 2/5 criteria. What typically happens to stocks in this criteria range?"

Questions that will not work:

"Should I buy HONASA?"
The AI will decline this. PineX blocks this type of question.

Your analyst helps you think. They do not think for you.$en$,
$hi$जो सवाल अच्छे काम करते हैं:

"HONASA 47 दिनों से advancing trend में है। Cycle analysis इस stage के stocks के बारे में क्या कहती है?"

"Pharma sector में 71% breadth है। Broad sector participation individual stocks को कैसे affect करती है?"

"BIOCON को देख रहा हूँ — 2/5 criteria हैं। इस criteria range के stocks में आमतौर पर क्या होता है?"

जो सवाल काम नहीं करेंगे:

"क्या HONASA खरीदूं?"
AI यह सवाल refuse करेगा। PineX इस type के सवाल block करता है।

AI आपको सोचने में मदद करता है। आपकी जगह सोचता नहीं।$hi$,
$ml$നല്ലതായ ചോദ്യങ്ങൾ:

"HONASA 47 ദിവസമായി advancing trend ൽ ആണ്. ഈ stage ൽ cycle analysis എന്ത് പറയുന്നു?"

"Pharma sector ൽ 71% breadth ആണ്. Broad sector participation individual stocks നെ എങ്ങനെ affect ചെയ്യും?"

"BIOCON നോക്കുന്നു — 2/5 criteria ഉണ്ട്. ഈ criteria range ഉള്ള stocks ന് സാധാരണ എന്ത് സംഭവിക്കും?"

ഈ ചോദ്യങ്ങൾ പറ്റില്ല:

"HONASA വാങ്ങണോ?"
AI ഈ ചോദ്യം refuse ചെയ്യും. PineX ഈ type ഉള്ള ചോദ്യങ്ങൾ block ചെയ്യും.

AI നിങ്ങളെ think ചെയ്യാൻ help ചെയ്യും. നിങ്ങൾക്ക് വേണ്ടി think ചെയ്യില്ല.$ml$,
$ta$நல்லாவே வேலை செய்யும் கேள்விகள்:

"HONASA 47 நாட்களா advancing trend-ல இருக்கு. இந்த stage-ல cycle analysis என்ன சொல்லுது?"

"Pharma sector-ல 71% breadth இருக்கு. Broad sector participation individual stocks-ஐ எப்படி affect பண்ணும்?"

"BIOCON-ஐ பாக்குறேன் — 2/5 criteria இருக்கு. இந்த criteria range-ல stocks-க்கு பொதுவா என்ன நடக்கும்?"

வேலை செய்யாத கேள்விகள்:

"HONASA வாங்கவா?"
AI இந்த கேள்வியை refuse பண்ணும். PineX இந்த type கேள்விகளை block செய்யும்.

AI உங்களை யோசிக்க help பண்ணும். உங்களுக்காக யோசிக்காது.$ta$,
'none', true),

-- ── Section 7 — Rotating your key ─────────────────────────────
('research_assistant', 7, 'Rotating your key',
$en$Your API key is like a password. Good practice is to replace it every few months.

Why rotate your key?
If you ever accidentally share your screen and someone sees it — a new key makes the old one useless.

How to rotate:
Go to aistudio.google.com
Create a new API key.
Go to PineX Settings.
Paste the new key.
Click Save.
Delete the old key from Google's dashboard.

PineX remembers nothing. The old key vanishes from your device the moment you save the new one.$en$,
$hi$आपकी API key एक password की तरह है। अच्छी practice है कि हर कुछ महीनों में इसे बदलें।

Key क्यों बदलें?
अगर कभी गलती से screen share करते समय कोई देख ले — नई key पुरानी को बेकार कर देती है।

कैसे बदलें:
aistudio.google.com पर जाएं।
नई API key बनाएं।
PineX Settings पर जाएं।
नई key paste करें।
Save click करें।
Google dashboard से पुरानी key delete करें।

PineX कुछ याद नहीं रखता। Save करते ही पुरानी key आपके device से चली जाती है।$hi$,
$ml$API key ഒരു password പോലെ ആണ്. ഏതാനും മാസം കൂടുമ്പോൾ മാറ്റുന്നത് നല്ലതാണ്.

Key എന്തിന് rotate ചെയ്യണം?
Screen share ചെയ്യുമ്പോൾ ആരെങ്കിലും കണ്ടുപോയാൽ — പുതിയ key പഴയതിനെ useless ആക്കുന്നു.

എങ്ങനെ rotate ചെയ്യാം:
aistudio.google.com ൽ പോകൂ.
പുതിയ API key create ചെയ്യൂ.
PineX Settings ൽ പോകൂ.
പുതിയ key paste ചെയ്ത് Save click ചെയ്യൂ.
Google dashboard ൽ നിന്ന് പഴയ key delete ചെയ്യൂ.

PineX ഒന്നും ഓർക്കില്ല. Save ചെയ്ത നിമിഷം പഴയ key നിങ്ങളുടെ device ൽ നിന്ന് പോകും.$ml$,
$ta$உங்க API key ஒரு password மாதிரி. ஒவ்வொரு சில மாதங்களிலும் மாற்றுவது நல்ல பழக்கம்.

ஏன் key-ஐ rotate செய்யணும்?
Screen share பண்றப்போ யாராவது தற்செயலா பாத்துட்டா — புது key பழசை useless ஆக்கும்.

எப்படி rotate செய்யணும்:
aistudio.google.com-க்கு போங்க.
புது API key create செய்யுங்க.
PineX Settings-க்கு போங்க.
புது key-ஐ paste செய்து Save click செய்யுங்க.
Google dashboard-ல இருந்து பழைய key-ஐ delete செய்யுங்க.

PineX எதையும் நினைவில் வைக்காது. Save செய்த நொடியே பழைய key உங்க device-ல இருந்து போய்விடும்.$ta$,
'none', true),

-- ── Section 8 — Deleting your key ─────────────────────────────
('research_assistant', 8, 'Deleting your key',
$en$Want to remove your key from PineX?

Go to Settings → Research Assistant.
Click "Delete key".
Your key is immediately erased from your device.

PineX never had it.
Now your device does not have it.
It is completely gone.

You can add a new key anytime.$en$,
$hi$Key हटाना चाहते हैं?

Settings → Research Assistant पर जाएं।
"Delete key" पर click करें।
Key तुरंत आपके device से मिट जाती है।

PineX के पास कभी थी नहीं।
अब आपके device पर भी नहीं।
बिल्कुल खत्म।

जब चाहें नई key add कर सकते हैं।$hi$,
$ml$Key remove ചെയ്യണോ?

Settings → Research Assistant ൽ പോകൂ.
"Delete key" click ചെയ്യൂ.
Key ഉടൻ device ൽ നിന്ന് delete ആകും.

PineX ന് ഒരിക്കലും ഉണ്ടായിരുന്നില്ല.
ഇനി device ൽ ഇല്ല.
പൂർണ്ണമായി പോയി.

എപ്പോൾ വേണമെങ്കിലും പുതിയ key add ചെയ്യാം.$ml$,
$ta$Key-ஐ remove செய்ய வேணுமா?

Settings → Research Assistant-க்கு போங்க.
"Delete key"-ஐ click செய்யுங்க.
Key உடனே உங்க device-ல இருந்து delete ஆகிடும்.

PineX-கிட்ட எப்போதும் இருந்ததில்ல.
இப்போ உங்க device-லயும் இல்ல.
முழுசா போயிடுச்சு.

எப்போ வேணும்னாலும் புது key add செய்யலாம்.$ta$,
'none', true),

-- ── Section 9 — The cost ──────────────────────────────────────
('research_assistant', 9, 'The cost',
$en$Gemini free tier:
15 questions per minute.
1,500 questions per day.
Cost: Rs.0.

For almost all traders:
The free tier is unlimited in practice.
Even 50 questions a day leaves you with 1,450 to spare.

If you want more:
Google charges approximately Rs.0.06 per question on paid tier.
100 questions = Rs.6.
A month of daily research = Rs.180.
Less than a cup of tea.$en$,
$hi$Gemini free tier:
एक मिनट में 15 सवाल।
एक दिन में 1,500 सवाल।
Cost: Rs.0।

ज्यादातर traders के लिए:
Free tier practically unlimited है।
दिन में 50 सवाल भी पूछें तो 1,450 बचे रहते हैं।

अगर ज्यादा चाहिए:
Google paid tier पर approximately Rs.0.06 प्रति सवाल लेता है।
100 सवाल = Rs.6।
महीने भर की daily research = Rs.180।
एक चाय से भी कम।$hi$,
$ml$Gemini free tier:
ഒരു മിനിറ്റിൽ 15 ചോദ്യങ്ങൾ.
ഒരു ദിവസം 1,500 ചോദ്യങ്ങൾ.
Cost: Rs.0.

മിക്ക traders നും:
Free tier practically unlimited ആണ്.
ദിവസം 50 ചോദ്യം ചോദിച്ചാലും 1,450 ബാക്കി ഉണ്ടാകും.

കൂടുതൽ വേണ്ടിവന്നാൽ:
Google paid tier ൽ ഒരു ചോദ്യത്തിന് ഏകദേശം Rs.0.06.
100 ചോദ്യങ്ങൾ = Rs.6.
ഒരു മാസത്തെ daily research = Rs.180.
ഒരു ചായയേക്കാൾ കുറവ്.$ml$,
$ta$Gemini free tier:
ஒரு நிமிஷத்துக்கு 15 கேள்விகள்.
ஒரு நாளுக்கு 1,500 கேள்விகள்.
Cost: Rs.0.

பெரும்பாலான traders-க்கு:
Free tier நடைமுறையில் வரம்பற்றது.
ஒரு நாளைக்கு 50 கேள்வி கேட்டாலும் 1,450 மிஞ்சும்.

அதிகம் வேணும்னா:
Google paid tier-ல ஒரு கேள்விக்கு ஏறக்குறைய Rs.0.06.
100 கேள்விகள் = Rs.6.
ஒரு மாசம் daily research = Rs.180.
ஒரு டீ விலையே குறைவு.$ta$,
'none', true);


-- ═════════════════════════════════════════════════════════════════
-- 4. Quiz questions (5 with 4 options each, correct_option is 1-based)
-- ═════════════════════════════════════════════════════════════════
DELETE FROM academy_questions WHERE module_id = 'research_assistant';

INSERT INTO academy_questions (
  module_id, sort_order,
  question_en, question_hi, question_ml, question_ta,
  option1_en, option1_hi, option1_ml, option1_ta,
  option2_en, option2_hi, option2_ml, option2_ta,
  option3_en, option3_hi, option3_ml, option3_ta,
  option4_en, option4_hi, option4_ml, option4_ta,
  correct_option,
  explanation_en, explanation_hi, explanation_ml, explanation_ta,
  is_published
) VALUES
-- Q1 — Where is your API key stored?
('research_assistant', 1,
 'Where is your API key stored?',
 'आपकी API key कहाँ store होती है?',
 'നിങ്ങളുടെ API key എവിടെ store ആകുന്നു?',
 'உங்க API key எங்க store ஆகுது?',
 'Only on your device',
 'सिर्फ आपके device पर',
 'നിങ്ങളുടെ device ൽ മാത്രം',
 'உங்க device-ல மட்டும்',
 'On PineX servers',
 'PineX servers पर',
 'PineX servers ൽ',
 'PineX servers-ல',
 'On Google servers',
 'Google servers पर',
 'Google servers ൽ',
 'Google servers-ல',
 'In a shared cloud database',
 'एक shared cloud database में',
 'ഒരു shared cloud database ൽ',
 'ஒரு shared cloud database-ல',
 1,
 'Your Gemini key is saved only in your browser localStorage. PineX servers never receive it.',
 'आपकी Gemini key केवल आपके browser के localStorage में save होती है। PineX servers को कभी नहीं मिलती।',
 'നിങ്ങളുടെ Gemini key നിങ്ങളുടെ browser localStorage ൽ മാത്രം save ആകുന്നു. PineX servers ന് ഒരിക്കലും കിട്ടില്ല.',
 'உங்க Gemini key உங்க browser localStorage-ல மட்டும்தான் save ஆகும். PineX servers-க்கு ஒருபோதும் கிடைக்காது.',
 true),

-- Q2 — Can PineX see your questions?
('research_assistant', 2,
 'Can PineX see your questions?',
 'क्या PineX आपके सवाल देख सकता है?',
 'PineX നിങ്ങളുടെ ചോദ്യങ്ങൾ കാണുമോ?',
 'PineX உங்க கேள்விகளை பாக்க முடியுமா?',
 'Yes — every question goes through PineX',
 'हाँ — हर सवाल PineX से होकर जाता है',
 'Yes — എല്ലാ ചോദ്യങ്ങളും PineX വഴി പോകുന്നു',
 'ஆமா — எல்லா கேள்விகளும் PineX வழியா போகுது',
 'Only if you choose to share them',
 'सिर्फ अगर आप share करना चुनें',
 'നിങ്ങൾ share ചെയ്താൽ മാത്രം',
 'நீங்க share பண்ண தேர்வு செய்தா மட்டும்',
 'No — never. Your device calls Google directly',
 'नहीं — कभी नहीं। आपका device सीधे Google को call करता है',
 'ഇല്ല — ഒരിക്കലുമില്ല. നിങ്ങളുടെ device നേരിട്ട് Google ലേക്ക് call ചെയ്യും',
 'இல்ல — ஒரு போதும் இல்ல. உங்க device நேரடியா Google-க்கு call பண்ணும்',
 'Only the admin can read them',
 'सिर्फ admin पढ़ सकता है',
 'Admin ന് മാത്രം വായിക്കാം',
 'Admin மட்டும் படிக்க முடியும்',
 3,
 'Your browser makes the request directly to Google''s Gemini API. PineX is not in the middle and cannot read either the question or the answer.',
 'आपका browser सीधे Google के Gemini API को request करता है। PineX बीच में नहीं है — न सवाल पढ़ सकता है न जवाब।',
 'നിങ്ങളുടെ browser നേരിട്ട് Google ന്റെ Gemini API ലേക്ക് request അയക്കും. PineX നടുവിൽ ഇല്ല — ചോദ്യമോ ഉത്തരമോ വായിക്കാൻ കഴിയില്ല.',
 'உங்க browser நேரடியா Google-ஓட Gemini API-க்கு request பண்ணும். PineX நடுவில இல்ல — கேள்வியோ பதிலோ படிக்க முடியாது.',
 true),

-- Q3 — How many free questions per day?
('research_assistant', 3,
 'How many questions per day on the free tier?',
 'Free tier पर एक दिन में कितने सवाल?',
 'Free tier ൽ ഒരു ദിവസം എത്ര ചോദ്യങ്ങൾ?',
 'Free tier-ல ஒரு நாளைக்கு எத்தனை கேள்விகள்?',
 '100',
 '100',
 '100',
 '100',
 '1,500',
 '1,500',
 '1,500',
 '1,500',
 '50',
 '50',
 '50',
 '50',
 'Unlimited',
 'असीमित',
 'പരിധി ഇല്ലാത്തത്',
 'வரம்பற்றது',
 2,
 'The Gemini free tier allows 15 questions per minute up to 1,500 per day. For nearly every trader that is effectively unlimited.',
 'Gemini free tier एक मिनट में 15 और एक दिन में 1,500 सवाल देता है। लगभग हर trader के लिए यह practically असीमित है।',
 'Gemini free tier ഒരു മിനിറ്റിൽ 15 ഉം ഒരു ദിവസം 1,500 ഉം ചോദ്യങ്ങൾ അനുവദിക്കുന്നു. മിക്കവാറും എല്ലാ traders നും practically unlimited.',
 'Gemini free tier ஒரு நிமிஷத்துக்கு 15-உம் ஒரு நாளுக்கு 1,500-உம் கேள்விகள் allow பண்ணும். கிட்டத்தட்ட எல்லா traders-க்கும் practically unlimited.',
 true),

-- Q4 — Which question should NOT be asked?
('research_assistant', 4,
 'Which question should you NOT ask the AI?',
 'AI से यह सवाल नहीं पूछना चाहिए?',
 'AI നോട് ഏത് ചോദ്യം ചോദിക്കരുത്?',
 'AI-கிட்ட எந்த கேள்வியை கேக்கக் கூடாது?',
 'What phase is HONASA in?',
 'HONASA किस phase में है?',
 'HONASA ഏത് phase ൽ ആണ്?',
 'HONASA எந்த phase-ல இருக்கு?',
 'Should I buy HONASA?',
 'क्या HONASA खरीदूं?',
 'HONASA വാങ്ങണോ?',
 'HONASA வாங்கவா?',
 'How does sector breadth work?',
 'Sector breadth कैसे काम करती है?',
 'Sector breadth എങ്ങനെ പ്രവർത്തിക്കും?',
 'Sector breadth எப்படி வேலை செய்யுது?',
 'What does cycle analysis say about Stage 2?',
 'Cycle analysis Stage 2 के बारे में क्या कहती है?',
 'Cycle analysis Stage 2 നെ പറ്റി എന്ത് പറയുന്നു?',
 'Cycle analysis Stage 2-ஐ பத்தி என்ன சொல்லுது?',
 2,
 'PineX blocks buy/sell/recommend-style questions. Your assistant explains data and concepts — investment decisions are yours to make (consult a SEBI registered adviser).',
 'PineX buy/sell/recommend जैसे सवाल block करता है। AI data और concepts समझाता है — निवेश के निर्णय आपके हैं (SEBI registered adviser से सलाह लें)।',
 'PineX buy/sell/recommend type ഉള്ള ചോദ്യങ്ങൾ block ചെയ്യും. AI data യും concepts ഉം വിശദീകരിക്കും — investment തീരുമാനങ്ങൾ നിങ്ങളുടേതാണ് (SEBI registered adviser നെ സമീപിക്കുക).',
 'PineX buy/sell/recommend மாதிரி கேள்விகளை block பண்ணும். AI data-வையும் concepts-ஐயும் விளக்கும் — investment decisions உங்களோடது (SEBI registered adviser-ஐ அணுகுங்க).',
 true),

-- Q5 — Why rotate the key?
('research_assistant', 5,
 'Why should you rotate your API key occasionally?',
 'API key कभी-कभी क्यों बदलनी चाहिए?',
 'API key എന്തുകൊണ്ട് occasionally rotate ചെയ്യണം?',
 'API key-ஐ ஏன் occasionally rotate செய்யணும்?',
 'PineX requires it',
 'PineX इसकी मांग करता है',
 'PineX ഇത് ആവശ്യപ്പെടുന്നു',
 'PineX கேக்குது',
 'Google charges more for old keys',
 'पुरानी keys के लिए Google ज्यादा charge करता है',
 'പഴയ keys ന് Google കൂടുതൽ charge ചെയ്യും',
 'பழைய keys-க்கு Google அதிக charge பண்ணும்',
 'Security — if someone saw it, a new key makes the old one useless',
 'Security — अगर किसी ने देख ली हो, नई key पुरानी को बेकार कर देती है',
 'Security — ആരെങ്കിലും കണ്ടെങ്കിൽ, പുതിയ key പഴയതിനെ useless ആക്കും',
 'Security — யாராவது பாத்திருந்தா, புது key பழசை useless ஆக்கும்',
 'It improves answer quality',
 'इससे जवाब बेहतर मिलते हैं',
 'ഉത്തരത്തിന്റെ ഗുണനിലവാരം മെച്ചപ്പെടും',
 'பதில் தரம் மேம்படும்',
 3,
 'Rotation is a security hygiene practice. If your key was ever exposed (accidental screen-share, photo of your monitor) a fresh key invalidates the old one.',
 'Rotation एक security practice है। अगर key कभी expose हो जाए (accidental screen-share, monitor की photo), नई key पुरानी को invalid कर देती है।',
 'Rotation ഒരു security practice ആണ്. Key എപ്പോഴെങ്കിലും expose ആയാൽ (accidental screen-share, monitor ന്റെ photo), പുതിയ key പഴയതിനെ invalid ആക്കും.',
 'Rotation ஒரு security practice. Key என்னவோ ஒரு சந்தர்ப்பத்துல expose ஆனா (accidental screen-share, monitor-ஓட photo), புது key பழசை invalid ஆக்கும்.',
 true);


-- ═════════════════════════════════════════════════════════════════
-- Verification — run after to confirm
-- ═════════════════════════════════════════════════════════════════
-- SELECT id, title_en, sort_order, is_pro, points_on_complete, is_published FROM academy_modules WHERE id = 'research_assistant';
-- SELECT COUNT(*) FROM academy_lessons   WHERE module_id = 'research_assistant';  -- expect 9
-- SELECT COUNT(*) FROM academy_questions WHERE module_id = 'research_assistant';  -- expect 5
