/**
 * StockDetail — "Quiet Clarity" redesign.
 *
 * The page is intentionally narrative-first. It reads as a cycle
 * essay, not a dashboard. Five fixed-title accordions surface the
 * Gemini-authored description on demand; the fifth accordion is a
 * HARDCODED stoploss philosophy answer (same on every stock) — never
 * AI-generated. A Pro gate accordion sits below the cycle content.
 *
 * Hard rules encoded here:
 *   - NO raw price numbers anywhere on the page.
 *   - Banned words in the narrative: buy / sell / invest / target /
 *     stoploss / support / resistance. We trust Gemini upstream not
 *     to produce these, but a runtime check logs a warning to the
 *     console if any slip through.
 *   - The SEBI disclaimer footer is ALWAYS rendered, no conditional.
 *   - Animation is spring(300, 35) — controlled, never bouncy.
 */
import { useEffect, useMemo, useState, lazy, Suspense } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import { motion, AnimatePresence } from 'framer-motion'
import { ArrowLeft, Plus, Lock } from 'lucide-react'
import { C } from '../styles/tokens'
import { useAuth } from '../context'
import { supabase } from '../lib/supabase'
import {
  insertWatchlistRow,
  selectWatchMembership,
  deleteWatchlistRow,
} from '../lib/watchlistTable'
import Skeleton from '../components/ui/Skeleton'
import SectionLabel from '../components/ui/SectionLabel'
// Lazy on both — SimilarStocks already mounts deferred via rIC, and
// CriteriaChart pulls in recharts (~424 KB / 119 KB gzip vendor-charts
// chunk). Direct imports were dragging that whole chunk onto the
// critical path for the stock detail page. With lazy() + Suspense,
// vendor-charts only loads when CriteriaChart actually mounts, which
// is post-paint. Net win on cold mobile: 100+ KB off the initial JS
// download.
const SimilarStocks = lazy(() => import('../components/SimilarStocks'))
const CriteriaChart = lazy(() => import('../components/CriteriaChart'))
// Code-split ResearchAssistant — it's ~50 KB (framer-motion logic +
// per-category prompt builders + multi-turn state) and renders below
// the fold on first paint. Lazy-loading shrinks the StockDetail entry
// chunk and shaves ~150ms off the parse cost on slower CPUs.
const ResearchAssistant = lazy(() =>
  import('../components/ResearchAssistant'),
)

// ── Constants ──────────────────────────────────────────────────────

// Map description.phase → reader-facing phase label. The five values
// below are the only labels rendered in the hero; anything else falls
// through to a quiet em-dash so we don't leak Gemini noise into the UI.
const PHASE_LABELS = {
  advancing: 'Advancing',
  basing: 'Basing',
  topping: 'Topping',
  declining: 'Declining',
}

// Words the cycle narrative MUST NOT contain. Upstream Gemini is
// instructed to avoid them; this list is the runtime safety net.
const BANNED_NARRATIVE_WORDS = [
  'buy',
  'sell',
  'invest',
  'target',
  'stoploss',
  'support',
  'resistance',
]

// Hardcoded answer for the fifth accordion. Identical for every
// stock — this is a philosophy statement, not stock-specific advice,
// and is deliberately NOT generated by Gemini.
const STOPLOSS_ANSWER = `We don't show stoplosses on PineX. A stoploss is a personal risk decision — it depends on your position size, your timeframe and the cycle phase you're trading. Two people looking at the same stock will reasonably choose different exits. What we do show is the cycle picture: phase, criteria, trend and participation. The exit level is yours to set.`

// Accordion titles 1–4 read from these description fields. Title 5
// is hardcoded above. Order matters — this is the reading sequence.
const CYCLE_ACCORDIONS = [
  { title: "What's happening in this stock right now?",    field: 'whats_happening' },
  { title: 'Why is this phase what it is?',                field: 'why_this_phase' },
  { title: 'What changes the picture?',                    field: 'what_changes' },
  { title: 'How does this fit the broader cycle?',         field: 'broader_cycle' },
]

const SPRING = { type: 'spring', stiffness: 300, damping: 35 }

// ── Module-level promise cache ─────────────────────────────────────
// Two perf wins in one Map:
//   1. React.StrictMode in dev double-invokes every useEffect. Without
//      this cache the main 4-way fetch fires TWICE on every mount in
//      dev — exactly the "slow localhost" Robin reported.
//   2. Back/forward navigation within the SPA session returns the
//      cached promise instead of refetching — instant transitions.
// Cache key is the uppercase symbol. Value is the in-flight Promise
// (also the resolved value once settled — same reference, no race).
// On fetch error we delete the entry so a retry can try again.
// We never invalidate on success: stock-detail data refreshes daily
// post-EOD, fine for a session lifetime. Hard-refresh forces re-pull.
const stockPageCache = new Map()

// Narrow select for stock_descriptions — only the fields the page
// actually renders. The earlier `.select('*')` pulled the entire row
// including the raw Gemini response, system prompt, and token-usage
// metadata (kilobytes per row). We render 14 named fields total.
const DESCRIPTION_FIELDS = [
  'phase',
  'narrative',
  'malayalam_line',
  'tagline_malayalam',
  'phase_streak_days',
  'streak_days',
  'criteria_score',
  'days_in_phase',
  'sector',
  'sector_breadth_pct',
  'whats_happening',
  'why_this_phase',
  'what_changes',
  'broader_cycle',
].join(',')

function loadStockPageData(rawSym) {
  if (!rawSym) return Promise.resolve(null)
  const key = String(rawSym).toUpperCase()
  if (stockPageCache.has(key)) return stockPageCache.get(key)

  const descP = supabase
    .from('stock_descriptions')
    .select(DESCRIPTION_FIELDS)
    .eq('symbol', key)
    .order('trading_date', { ascending: false })
    .limit(1)
    .maybeSingle()

  const compP = supabase
    .from('companies')
    .select('id, symbol, name, sector, market_cap')
    .eq('symbol', key)
    .maybeSingle()

  // condP widened from limit(1) → limit(60). Same query now powers
  // BOTH the most-recent conditions panel (consumer takes [0]) and the
  // 60-day CriteriaChart series — eliminating CriteriaChart's separate
  // round-trip on initial render. Net effect: one less Supabase query
  // per stock-detail mount.
  const condP = supabase
    .from('swing_conditions')
    .select('conditions_met, date, criteria_change_reason, companies!inner(symbol)')
    .eq('companies.symbol', key)
    .order('date', { ascending: false })
    .limit(60)

  // priceHistP narrowed from 252 (~1 yr) → 120 (~6 mo). The only
  // consumer is the Phase Duration Insight counter (walks newest-
  // first counting consecutive days in the current stage). 120 covers
  // every phase shorter than 6 months — the long tail past that just
  // reports "120+ trading days" which is fine semantically. Saves
  // ~50% of payload on the slowest of the 4 parallel queries.
  //
  // rs_vs_nifty added to the select so the header strip can render
  // "+30.6% vs Nifty ↑" next to the phase badge (squint-test row).
  // The column lives on price_data and is refreshed daily by
  // scripts/compute_mansfield_rs.py — `priceHistory[0]?.rs_vs_nifty`
  // is always the latest available value.
  const priceHistP = supabase
    .from('price_data')
    .select('date, stage, rs_vs_nifty, companies!inner(symbol)')
    .eq('companies.symbol', key)
    .order('date', { ascending: false })
    .limit(120)

  const promise = Promise.all([descP, compP, condP, priceHistP])
    .then(([d, c, s, ph]) => {
      const condRows = Array.isArray(s?.data) ? s.data : []
      return {
        description:        d?.data ?? null,
        company:            c?.data ?? null,
        conditions:         condRows[0] ?? null,
        conditionsHistory:  condRows,
        priceHistory:       Array.isArray(ph?.data) ? ph.data : [],
      }
    })
    .catch((err) => {
      stockPageCache.delete(key)
      throw err
    })

  stockPageCache.set(key, promise)
  return promise
}


// ── Local Accordion ────────────────────────────────────────────────

function Accordion({ title, body, isProGate = false }) {
  const [open, setOpen] = useState(false)
  return (
    <div
      style={{
        background: C.surface,
        border: `1px solid ${C.border}`,
        borderRadius: 12,
        overflow: 'hidden',
      }}
    >
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        className="w-full flex items-center justify-between text-left"
        style={{
          // 52px (not 48) gives extra room for Malayalam descenders /
          // ascenders that extend above and below the Latin cap height.
          // Padding kept symmetric inside the flex row so the title +
          // chevron align consistently on touch.
          minHeight: 52,
          padding: '14px 16px',
          background: 'transparent',
          border: 'none',
          cursor: 'pointer',
          color: C.text,
          fontFamily: 'Newsreader, ui-serif, Georgia, serif',
          fontSize: '1rem',
          fontWeight: 500,
          letterSpacing: '-0.01em',
        }}
      >
        <span style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          {isProGate && <Lock size={14} style={{ color: C.amber }} />}
          {title}
        </span>
        <span
          aria-hidden="true"
          style={{
            color: C.textMuted,
            fontSize: 18,
            transform: open ? 'rotate(45deg)' : 'rotate(0deg)',
            transition: 'transform 200ms ease',
            display: 'inline-flex',
          }}
        >
          <Plus size={16} />
        </span>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={SPRING}
            style={{ overflow: 'hidden' }}
          >
            <div
              style={{
                padding: '4px 18px 18px',
                color: C.textMuted,
                fontFamily: 'Newsreader, ui-serif, Georgia, serif',
                fontSize: '1rem',
                lineHeight: 1.75,
                borderTop: `1px solid ${C.border}`,
                paddingTop: 14,
              }}
            >
              {body}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// CTA body for the Pro gate accordion.
function ProGateContent({ onClick }) {
  return (
    <div>
      <p style={{ margin: 0, marginBottom: 14 }}>
        See which other stocks are currently in the same cycle phase
        with comparable structure and participation. Available with
        PineX Pro.
      </p>
      <button
        type="button"
        onClick={onClick}
        style={{
          background: C.amber,
          color: C.accentOn,
          border: 'none',
          borderRadius: 8,
          padding: '10px 18px',
          fontSize: 14,
          fontWeight: 600,
          cursor: 'pointer',
          letterSpacing: '0.01em',
          fontFamily: 'system-ui, -apple-system, sans-serif',
        }}
      >
        Explore PineX Pro
      </button>
    </div>
  )
}

// ── SEBI footer ────────────────────────────────────────────────────
// Always rendered — never conditional.
function SebiFooter() {
  return (
    <div
      style={{
        marginTop: 32,
        padding: '16px 18px',
        borderTop: `1px solid ${C.border}`,
        color: C.textFaint,
        fontSize: 11,
        lineHeight: 1.6,
        fontStyle: 'italic',
        textAlign: 'center',
      }}
    >
      Educational content only. Not investment advice or a recommendation
      to buy or sell any security. PineX is not a SEBI registered
      investment advisor. Past cycle patterns do not guarantee future
      performance. Consult a SEBI-registered advisor for personal
      recommendations.
    </div>
  )
}

// ── Component ──────────────────────────────────────────────────────

export default function StockDetail() {
  const { symbol } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()

  const sym = symbol?.toUpperCase()

  // Data state — `null` until first load resolves. We never render
  // raw prices, so we don't store price rows here.
  const [description, setDescription] = useState(null) // stock_descriptions row | null
  const [company, setCompany]         = useState(null) // companies row | null
  const [conditions, setConditions]   = useState(null) // swing_conditions row | null
  // Last 60 rows of swing_conditions — feeds CriteriaChart's series
  // prop so the chart no longer fires its own fetch. Newest-first;
  // CriteriaChart reverses internally.
  const [conditionsHistory, setConditionsHistory] = useState([])
  // Recent stage history — newest-first, last ~252 trading days
  // (≈ 1 year). Only `date` + `stage` are pulled so the Phase
  // Duration Insight line can count consecutive trading days the
  // stock has been in its current stage. We don't render any prices
  // or candles from this — the phase counter is the sole consumer.
  const [priceHistory, setPriceHistory] = useState([])
  const [loading, setLoading]         = useState(true)

  // Defers the SimilarStocks mount until after the main content has
  // painted. SimilarStocks fires its own price_data fetch (~25-row
  // pool) — letting it contend with the main 4-way fetch on initial
  // load makes the page feel jankier than it is. Flipping after a
  // short timeout (or rIC if available) lets the narrative + chart
  // + accordions render first, then SimilarStocks slots in.
  const [showSimilar, setShowSimilar] = useState(false)
  useEffect(() => {
    if (loading) return
    const rIC = typeof window !== 'undefined' && window.requestIdleCallback
    if (rIC) {
      const h = window.requestIdleCallback(() => setShowSimilar(true), { timeout: 1000 })
      return () => window.cancelIdleCallback?.(h)
    }
    const t = setTimeout(() => setShowSimilar(true), 250)
    return () => clearTimeout(t)
  }, [loading])

  // Watchlist state — same shape as the legacy file.
  const [watching, setWatching]           = useState(false)
  const [watchlistRowId, setWatchlistRowId] = useState(null)
  const [watchLoading, setWatchLoading]   = useState(false)
  const [watchError, setWatchError]       = useState(null)

  // ── Fetch on mount ───────────────────────────────────────────────
  // Delegates to the module-level loadStockPageData cache:
  //   - First mount: fires the 4-way Promise.all once, caches the
  //     in-flight Promise.
  //   - StrictMode's second invocation: returns the cached Promise.
  //     No second round-trip.
  //   - Back/forward to a previously-viewed stock: instant —
  //     cache returns the resolved Promise synchronously.
  // The narrowed DESCRIPTION_FIELDS select also drops the heavy
  // Gemini-prompt / token-usage columns we never render.
  useEffect(() => {
    if (!sym) return
    let cancelled = false
    setLoading(true)
    loadStockPageData(sym)
      .then((data) => {
        if (cancelled || !data) return
        setDescription(data.description)
        setCompany(data.company)
        setConditions(data.conditions)
        setConditionsHistory(data.conditionsHistory || [])
        setPriceHistory(data.priceHistory)
        setLoading(false)

        // Banned-word check on the narrative. Console-only — never
        // shown to the user. Catches Gemini drift early.
        const narrative = data.description?.narrative
        if (typeof narrative === 'string') {
          const lower = narrative.toLowerCase()
          const hit = BANNED_NARRATIVE_WORDS.find((w) =>
            new RegExp(`\\b${w}\\b`, 'i').test(lower),
          )
          if (hit) {
            // eslint-disable-next-line no-console
            console.warn(
              `[StockDetail] narrative for ${sym} contains banned word "${hit}". Upstream Gemini drift — please review.`,
            )
          }
        }
      })
      .catch(() => {
        if (!cancelled) setLoading(false)
      })
    return () => { cancelled = true }
  }, [sym])

  // ── Watchlist membership check (mirrors legacy) ─────────────────
  useEffect(() => {
    if (!user?.id || !company?.id) {
      setWatching(false)
      setWatchlistRowId(null)
      return
    }
    let cancelled = false
    selectWatchMembership(user.id, company.id).then(({ data }) => {
      if (cancelled) return
      if (data?.id) {
        setWatching(true)
        setWatchlistRowId(data.id)
      } else {
        setWatching(false)
        setWatchlistRowId(null)
      }
    })
    return () => { cancelled = true }
  }, [user?.id, company?.id])

  // ── Watchlist toggle — EXACT logic from the legacy file ─────────
  function humanizeWatchError(err) {
    const code = err?.code
    const msg = err?.message || ''
    if (code === '42501' || msg.includes('row-level security')) {
      return 'Permission denied — please sign in again.'
    }
    if (code === '23505') {
      return 'Already in your watchlist.'
    }
    if (msg.toLowerCase().includes('jwt') || msg.includes('401')) {
      return 'Session expired — please sign in again.'
    }
    return 'Could not update watchlist. Please try again.'
  }

  const handleWatchToggle = async () => {
    if (!user) {
      navigate('/login', { state: { next: `/stock/${sym}` } })
      return
    }
    if (watchLoading) return
    if (!company?.id) {
      setWatchError('Stock data is still loading — please try again in a moment.')
      return
    }
    setWatchLoading(true)
    setWatchError(null)
    try {
      if (watching && watchlistRowId) {
        const { error: delErr } = await deleteWatchlistRow(user.id, watchlistRowId)
        if (delErr) {
          setWatchError(humanizeWatchError(delErr))
          return
        }
        setWatching(false)
        setWatchlistRowId(null)
      } else {
        // Note: legacy passes `price_at_add: price?.close ?? null`.
        // Quiet Clarity never reads price into component state, so we
        // omit it — the column is nullable and the row still saves.
        const { data, error } = await insertWatchlistRow({
          user_id: user.id,
          company_id: company.id,
          symbol: sym,
          group_name: 'My Watchlist',
          added_at: new Date().toISOString(),
          price_at_add: null,
        })
        if (error) {
          setWatchError(humanizeWatchError(error))
          return
        }
        setWatching(true)
        setWatchlistRowId(data?.id ?? null)
      }
    } catch (e) {
      setWatchError(humanizeWatchError(e))
    } finally {
      setWatchLoading(false)
    }
  }

  // ── Derived display values ──────────────────────────────────────
  const phaseRaw = description?.phase
  const phaseLabel = phaseRaw ? (PHASE_LABELS[String(phaseRaw).toLowerCase()] || null) : null
  const streak = description?.phase_streak_days ?? description?.streak_days ?? null
  const malayalam = description?.malayalam_line || description?.tagline_malayalam || null
  const narrative = description?.narrative || null
  const criteriaScore = conditions?.conditions_met ?? null

  // ── Phase Duration Insight ─────────────────────────────────────────
  // "Day N of <Phase> phase · Typical: ~M days"  (or "Extended").
  //
  // Walks priceHistory (newest-first) counting consecutive trading
  // days the stock has been in its current stage. Hardcoded AVG_DAYS
  // are the typical durations across NSE cycle data — placeholder
  // until we wire a per-stock backfill. Updating the table here
  // moves the entire site; no migration needed.
  //
  // Returns null when:
  //   - priceHistory hasn't loaded yet
  //   - the newest row has no stage or stage is "unclassified"
  //   - somehow zero consecutive rows match (shouldn't happen but
  //     defensive)
  // Callers conditionally render — null → no line, no layout shift.
  const phaseDuration = useMemo(() => {
    const AVG_DAYS = {
      stage1: 120,
      stage2: 180,
      stage3: 45,
      stage4: 90,
    }
    const STAGE_NAMES = {
      stage1: 'Basing',
      stage2: 'Advancing',
      stage3: 'Topping',
      stage4: 'Declining',
    }
    const normalise = (s) => String(s || '').toLowerCase().replace(/\s+/g, '')
    // The "current" stage is whichever stage the newest priceHistory
    // row carries. We deliberately key off priceHistory[0] (not
    // description.phase) so the count's terminus and origin come
    // from the same dataset — no off-by-one if description.phase
    // disagreed with the latest price row.
    const newest = priceHistory?.[0]
    const currentNorm = normalise(newest?.stage)
    if (!currentNorm || currentNorm === 'unclassified') return null

    let count = 0
    for (const row of priceHistory) {
      if (normalise(row?.stage) === currentNorm) count++
      else break
    }
    if (count === 0) return null

    const avg = AVG_DAYS[currentNorm] ?? null
    const stageName = STAGE_NAMES[currentNorm] ?? 'current'
    return {
      daysInPhase: count,
      avg,
      stageName,
      isExtended: avg ? count > avg : false,
    }
  }, [priceHistory])

  // Phase → top-border colour for the narrative card. Mirrors the
  // semantic phase palette used everywhere else in the app:
  //   Advancing → green   (healthy / positive)
  //   Basing    → amber   (caution / sideways)
  //   Topping   → red     (risk)
  //   Declining → red     (risk)
  //   Unknown   → border  (neutral / pending)
  const narrativeBorderColor = (() => {
    const p = phaseRaw ? String(phaseRaw).toLowerCase() : null
    if (p === 'advancing') return C.green
    if (p === 'basing')    return C.amber
    if (p === 'topping' || p === 'declining') return C.red
    return C.border
  })()

  // ── Render ───────────────────────────────────────────────────────
  return (
    <>
      <Helmet>
        <title>{company?.name || sym || symbol} — PineX</title>
        <meta
          name="description"
          content={
            narrative?.slice(0, 160) ||
            `Cycle analysis for ${sym || symbol} on PineX`
          }
        />
      </Helmet>

      <div
        style={{
          minHeight: '100vh',
          background: C.base,
          color: C.text,
          fontFamily: 'system-ui, -apple-system, sans-serif',
        }}
      >
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={SPRING}
          className="mx-auto"
          style={{ maxWidth: 720, padding: '24px 20px 48px' }}
        >
          {/* ── HERO ─────────────────────────────────────────── */}
          <div className="flex items-center justify-between" style={{ marginBottom: 24 }}>
            <button
              type="button"
              onClick={() => navigate(-1)}
              className="inline-flex items-center"
              style={{
                gap: 6,
                background: 'transparent',
                border: 'none',
                color: C.textMuted,
                fontSize: 13,
                cursor: 'pointer',
                padding: '6px 0',
              }}
            >
              <ArrowLeft size={14} />
              <span>Back</span>
            </button>
            <button
              type="button"
              onClick={handleWatchToggle}
              disabled={watchLoading}
              style={{
                background: watching ? C.accentBg : 'transparent',
                color: watching ? C.amber : C.textMuted,
                border: `1px solid ${watching ? C.amber : C.border}`,
                borderRadius: 999,
                padding: '6px 14px',
                fontSize: 12,
                fontWeight: 600,
                cursor: watchLoading ? 'wait' : 'pointer',
                letterSpacing: '0.02em',
              }}
            >
              {watchLoading
                ? 'Saving…'
                : watching
                ? 'On your watchlist'
                : '+ Watchlist'}
            </button>
          </div>

          {loading ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <Skeleton height={32} width="60%" />
              <Skeleton height={20} width="40%" />
              {/* 5-line paragraph skeleton — sits where the narrative
                  prose will land so the user's eye doesn't jump when
                  the real text streams in. Varying widths (100/80/90/
                  70/85%) read like a real broken-line paragraph. The
                  global `pulse` keyframes live in src/index.css. */}
              <div style={{ maxWidth: '65ch', marginTop: 16 }}>
                {[1, 0.8, 0.9, 0.7, 0.85].map((w, i) => (
                  <div
                    key={i}
                    style={{
                      height: 16,
                      width: `${w * 100}%`,
                      background: C.surface2,
                      borderRadius: 4,
                      marginBottom: 10,
                      animation: 'pulse 1.5s infinite',
                    }}
                  />
                ))}
              </div>
            </div>
          ) : (
            <>
              {/* Company name + phase */}
              <h1
                style={{
                  margin: 0,
                  fontFamily: 'Newsreader, ui-serif, Georgia, serif',
                  fontSize: '2rem',
                  fontWeight: 500,
                  letterSpacing: '-0.02em',
                  color: C.textHeading,
                  lineHeight: 1.15,
                }}
              >
                {company?.name || sym}
              </h1>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 10,
                  flexWrap: 'wrap',
                  marginTop: 10,
                  marginBottom: 6,
                }}
              >
                <span
                  style={{
                    color: C.textMuted,
                    fontSize: 13,
                    letterSpacing: '0.03em',
                  }}
                >
                  {sym}
                </span>
                {phaseLabel && (
                  <span
                    style={{
                      background: C.accentBg,
                      color: C.amber,
                      border: `1px solid ${C.accentMuted}`,
                      borderRadius: 999,
                      padding: '2px 10px',
                      fontSize: 11,
                      fontWeight: 700,
                      letterSpacing: '0.06em',
                      textTransform: 'uppercase',
                    }}
                  >
                    {phaseLabel}
                  </span>
                )}
                {/* RS vs Nifty — passes the squint test. Reads the
                    rs_vs_nifty column from the latest price_data row
                    (refreshed daily by compute_mansfield_rs.py). Sits
                    next to the phase badge so a user sees phase + RS
                    without scrolling or reading body copy. Hidden if
                    the value is null / non-numeric — keeps the row
                    clean on stocks where RS hasn't computed yet. */}
                {(() => {
                  const rs = Number(priceHistory[0]?.rs_vs_nifty)
                  if (!Number.isFinite(rs)) return null
                  const positive = rs >= 0
                  const sign = positive ? '+' : ''
                  return (
                    <span
                      style={{
                        color: positive ? C.green : C.red,
                        fontSize: 13,
                        fontWeight: 700,
                        letterSpacing: '-0.01em',
                      }}
                      title="Relative strength vs Nifty 50 over the last 52 weeks"
                    >
                      {sign}{rs.toFixed(1)}% vs Nifty {positive ? '↑' : '↓'}
                    </span>
                  )
                })()}
                {streak != null && (
                  <span style={{ color: C.textFaint, fontSize: 12 }}>
                    {streak} days {'🔥'}
                  </span>
                )}
              </div>

              {/* Phase Duration Insight — single line, render-or-omit.
                  Colour split: amber when extended (current days >
                  typical avg), muted otherwise. Reads as a neutral
                  data observation ("Day 47 of Advancing phase ·
                  Typical: ~180 days") — does not advise the reader. */}
              {phaseDuration ? (
                <p style={{
                  margin: '6px 0 0',
                  fontSize: 13,
                  color: phaseDuration.isExtended ? '#FBBF24' : '#64748B',
                }}>
                  Day {phaseDuration.daysInPhase} of {phaseDuration.stageName} phase
                  {phaseDuration.avg
                    ? phaseDuration.isExtended
                      ? ` · Extended (avg ~${phaseDuration.avg} days)`
                      : ` · Typical: ~${phaseDuration.avg} days`
                    : null}
                </p>
              ) : null}

              {/* Malayalam line — lang="ml" hooks the [lang="ml"]
                  selector in src/index.css which swaps in Noto Sans
                  Malayalam + bumps line-height to 1.9 so descenders
                  don't clip. The inline fontFamily is overridden by
                  the CSS rule (Malayalam fallback first); fontStyle
                  + letterSpacing stay. */}
              {malayalam && (
                <p
                  lang="ml"
                  style={{
                    margin: '6px 0 0',
                    color: C.textMuted,
                    fontStyle: 'italic',
                    fontSize: '1rem',
                    letterSpacing: '-0.005em',
                  }}
                >
                  {malayalam}
                </p>
              )}

              {watchError && (
                <p
                  style={{
                    marginTop: 10,
                    color: C.red,
                    fontSize: 12,
                  }}
                >
                  {watchError}
                </p>
              )}

              {/* ── NARRATIVE ──────────────────────────────────
                  Card-style wrapper with a 4-px phase-coloured top
                  border. Inner text is capped at 65ch — optimal
                  reading-width on tablet/desktop; on mobile (390 px)
                  the screen is narrower than 65ch anyway so the cap
                  has no visual effect. */}
              <div
                style={{
                  marginTop: 32,
                  borderTop: `4px solid ${narrativeBorderColor}`,
                  background: C.surface,
                  borderLeft: `1px solid ${C.border}`,
                  borderRight: `1px solid ${C.border}`,
                  borderBottom: `1px solid ${C.border}`,
                  borderRadius: '0 0 12px 12px',
                  padding: '18px 18px 20px',
                }}
              >
                {narrative ? (
                  <div style={{ maxWidth: '65ch' }}>
                    <p
                      style={{
                        margin: 0,
                        color: C.text,
                        fontFamily: 'Newsreader, ui-serif, Georgia, serif',
                        fontSize: '1.05rem',
                        lineHeight: 1.7,
                        letterSpacing: '-0.005em',
                      }}
                    >
                      {narrative}
                    </p>

                    {/* 5 criteria dots — one dot per criterion. Lit
                        dots = criteria met. No labels, no numbers
                        beyond the dot pattern. */}
                    <div
                      style={{
                        display: 'flex',
                        gap: 8,
                        marginTop: 18,
                        alignItems: 'center',
                      }}
                      aria-label={
                        criteriaScore != null
                          ? `${criteriaScore} of 5 criteria met`
                          : 'Criteria score unavailable'
                      }
                    >
                      {[0, 1, 2, 3, 4].map((i) => {
                        const lit = criteriaScore != null && i < Number(criteriaScore)
                        return (
                          <span
                            key={i}
                            style={{
                              width: 8,
                              height: 8,
                              borderRadius: 999,
                              background: lit ? C.amber : C.surface2,
                              border: `1px solid ${lit ? C.amber : C.border}`,
                              display: 'inline-block',
                            }}
                          />
                        )
                      })}
                      <span
                        style={{
                          marginLeft: 6,
                          fontSize: 11,
                          color: C.textFaint,
                          letterSpacing: '0.04em',
                          textTransform: 'uppercase',
                        }}
                      >
                        {criteriaScore != null ? `${criteriaScore}/5` : '—/5'}
                      </span>
                    </div>

                    {/* "Changed today" badge — reads the pipeline-
                        written reason from the SAME swing_conditions
                        row the dots above reflect. Single source of
                        truth: when conditions.date is today the reason
                        applies; on weekends/holidays the dots show
                        Friday's data and the reason (if any) matches.
                        No separate criteria_changes query needed.

                        Reason text is built server-side from a fixed
                        labels dict ("Strengthening - Added: Above
                        long-term trend" etc.) — neutral data-class-
                        ification, never prescriptive, safe to render
                        directly. */}
                    {conditions?.criteria_change_reason ? (
                      <div
                        style={{
                          marginTop: 8,
                          fontSize: 12,
                          color: C.amber,
                          lineHeight: 1.5,
                        }}
                      >
                        Changed today: {conditions.criteria_change_reason}
                      </div>
                    ) : null}
                  </div>
                ) : (
                  <p
                    style={{
                      textAlign: 'center',
                      color: C.textMuted,
                      fontFamily: 'Newsreader, ui-serif, Georgia, serif',
                      fontSize: '1rem',
                      lineHeight: 1.7,
                      padding: '24px 12px',
                    }}
                  >
                    Analysis for this stock is being prepared. Check back
                    after market close today.
                  </p>
                )}
              </div>

              {/* ── Criteria Evolution Chart ──────────────────────
                  60-day journey of the SwingX conditions_met score
                  (0-5). Sits right after the narrative card where
                  the current criteria dots already render — same
                  data point, shown over time.

                  CriteriaChart is self-contained: owns its own
                  SectionLabel header + 28-px top margin. When
                  swing_conditions history is too thin (< 2 rows)
                  the entire block — heading included — returns
                  null, so the page reads cleanly. The previous
                  outer SectionLabel was producing the empty-
                  section bug visible on thin-history stocks like
                  BLISSGVS. */}
              <Suspense fallback={null}>
                <CriteriaChart symbol={sym} series={conditionsHistory} />
              </Suspense>

              {/* ── Research Assistant (BYOK Gemini) — Pro feature.
                  Self-gates render: shows the no-key teaser when the
                  user is Pro-eligible but hasn't pasted a key, the
                  active panel when both Pro + key are present. The
                  Pro check uses usePlan().canAccess() but with
                  OPEN_FREE=true everyone is treated as Pro right now
                  — primes for paywall launch.
                  Moved above the accordion list so the higher-value
                  open-ended question entry point is the first thing a
                  user sees after the narrative. */}
              {/* Reserved-height wrapper so the lazy-load swap-in
                  doesn't push the accordion list down (CLS). 500px
                  matches the rendered footprint of the 7-tile menu +
                  header + footer on mobile, so when the real component
                  arrives, no visible shift. */}
              <div style={{ marginTop: 28, minHeight: 500 }}>
                <Suspense
                  fallback={
                    <div
                      aria-hidden
                      style={{
                        height: 500,
                        borderRadius: 14,
                        background:
                          'linear-gradient(180deg, rgba(245,159,11,0.04) 0%, rgba(245,159,11,0) 100%)',
                        border: '1px solid rgba(245,159,11,0.10)',
                      }}
                    />
                  }
                >
                  <ResearchAssistant
                    symbol={sym}
                    companyName={company?.name}
                    phase={description?.phase}
                    criteriaScore={description?.criteria_score ?? conditions?.conditions_met}
                    daysInPhase={description?.days_in_phase}
                    sector={company?.sector || description?.sector}
                    sectorBreadth={description?.sector_breadth_pct}
                    narrative={description?.narrative}
                    pctFromMA={conditions?.pct_from_ma}
                    userId={user?.id}
                  />
                </Suspense>
              </div>

              {/* ── ACCORDIONS 1–5 ──────────────────────────── */}
              <div
                style={{
                  marginTop: 32,
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 10,
                }}
              >
                {CYCLE_ACCORDIONS.map((a) => {
                  const body = description?.[a.field]
                  return (
                    <Accordion
                      key={a.field}
                      title={a.title}
                      body={
                        body || (
                          <span style={{ color: C.textFaint }}>
                            Not available for this stock yet.
                          </span>
                        )
                      }
                    />
                  )
                })}
                {/* Fifth accordion — HARDCODED stoploss answer. */}
                <Accordion
                  title="Where should I set my stoploss?"
                  body={STOPLOSS_ANSWER}
                />
              </div>

              {/* ── Stocks in similar condition ──────────────────
                  Lists up to 5 stocks sharing this stock's current
                  stage, preferring the same sector. Replaces the
                  earlier Pro-gated "Show me similar stocks" teaser
                  accordion — the feature now ships for everyone.
                  SimilarStocks self-gates on having ≥ 2 results so
                  the heading doesn't sit alone if the cohort is
                  thin. The condition on priceHistory[0]?.stage
                  ensures we don't render the section heading at all
                  while the price-history fetch is still pending. */}
              {showSimilar && priceHistory[0]?.stage ? (
                <div style={{ marginTop: 28 }}>
                  <SectionLabel text="Stocks in similar condition" />
                  <Suspense fallback={null}>
                    <SimilarStocks
                      currentSymbol={sym}
                      currentStage={priceHistory[0]?.stage}
                      currentSector={company?.sector}
                    />
                  </Suspense>
                </div>
              ) : null}
            </>
          )}

          {/* ── SEBI footer — always rendered, no exceptions ── */}
          <SebiFooter />
        </motion.div>
      </div>
    </>
  )
}
